# RD
rd.meta=http://meta.apollo.hkbackend.com
quark.meta=http://120.55.48.215:8080
# PROD
online.meta=http://meta.apollo.homeking365.com/
# QA
qa.meta=http://meta.apollo.hktqa.cn
#内网地址
#qa.meta=http://meta.apollo.dev-hktqa.cn
