server.port=9090
# Apollo APP名称
app.id=service-license
# 服务器地址
#apollo.meta=http://192.168.100.19:8080
# 引导阶段会注入
apollo.bootstrap.enabled=true
# 将初始化放在日志系统初始化之前
apollo.bootstrap.eagerLoad.enabled=false
# 命名空间
apollo.bootstrap.namespaces=application,spring-datasource,mybatis-plus,spring-dubbo,spring-redis,idworker,LTS,mq,rmongo,message,spring-email,TDC.common, TDC.accounts,xxljob
# 缓存文件地址
apollo.cacheDir=apollo/
# 配置日志地址
logging.config=classpath:logback/logback-spring.xml
#Metrics related configurations
management.server.port=9999
management.endpoints.web.base-path=/
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
#management.security.enabled=false
#endpoints.prometheus.sensitive=false
# 访问 <addr>:9999/prometheus 即可看到 prometheus 监控项
#打印查询sql及参数
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
